import type { House } from './types';

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const datas: House[] = [
  {
    id: 1,
    name: 'Villa moderne avec piscine',
    emplacement: { ville: 'Ouagadougou', quartier: 'Ouaga 2000' },
    description:
      "Superbe villa contemporaine avec piscine privée, grand jardin arboré et terrasse couverte idéale pour recevoir.",
    contact: '+226 70 12 34 56',
    prix: 250000,
    image: img('photo-1600596542815-ffad4c1539a9'),
    chambres: 4,
    sdb: 3,
    surface: 250,
    categorie: 'villa',
    equipements: ['Piscine', 'Jardin', 'Garage', 'Climatisation', 'Groupe électrogène'],
    nouveau: true,
  },
  {
    id: 2,
    name: 'Appartement cosy au centre-ville',
    emplacement: { ville: 'Ouagadougou', quartier: 'Koulouba' },
    description:
      "Appartement lumineux entièrement rénové, proche des commerces, des écoles et des services administratifs.",
    contact: '+226 76 22 33 44',
    prix: 90000,
    image: img('photo-1502672260266-1c1ef2d93688'),
    chambres: 2,
    sdb: 1,
    surface: 75,
    categorie: 'appartement',
    equipements: ['Climatisation', 'Wi-Fi', 'Balcon', 'Eau courante'],
    nouveau: false,
  },
  {
    id: 3,
    name: 'Studio meublé',
    emplacement: { ville: 'Ouagadougou', quartier: 'Zogona' },
    description:
      "Studio pratique et entièrement meublé, idéal pour étudiant ou jeune actif à la recherche d'indépendance.",
    contact: '+226 65 44 55 66',
    prix: 45000,
    image: img('photo-1522708323590-d24dbb6b0267'),
    chambres: 1,
    sdb: 1,
    surface: 30,
    categorie: 'studio',
    equipements: ['Meublé', 'Wi-Fi', 'Climatisation'],
    nouveau: true,
  },
  {
    id: 4,
    name: 'Duplex familial',
    emplacement: { ville: 'Ouagadougou', quartier: 'Gounghin' },
    description:
      "Grand duplex avec cour privée, garage pour deux voitures et espaces de vie spacieux pour toute la famille.",
    contact: '+226 78 11 22 33',
    prix: 180000,
    image: img('photo-1568605114967-8130f3a36994'),
    chambres: 5,
    sdb: 3,
    surface: 180,
    categorie: 'maison',
    equipements: ['Garage', 'Jardin', 'Groupe électrogène', 'Sécurité 24h'],
    nouveau: false,
  },
  {
    id: 5,
    name: 'Villa de standing',
    emplacement: { ville: 'Ouagadougou', quartier: "Patte d'Oie" },
    description:
      "Villa haut standing avec piscine, jardin paysager et espace détente dans un quartier résidentiel prisé.",
    contact: '+226 70 99 88 77',
    prix: 400000,
    image: img('photo-1512917774080-9991f1c4c750'),
    chambres: 6,
    sdb: 5,
    surface: 400,
    categorie: 'villa',
    equipements: ['Piscine', 'Jardin', 'Garage', 'Climatisation', 'Sécurité 24h'],
    nouveau: true,
  },
  {
    id: 6,
    name: 'Appartement moderne',
    emplacement: { ville: 'Ouagadougou', quartier: 'Tanghin' },
    description:
      "Appartement moderne avec balcon ensoleillé, cuisine équipée et climatisation dans toutes les pièces.",
    contact: '+226 77 66 55 44',
    prix: 110000,
    image: img('photo-1507089947368-19c1da9775ae'),
    chambres: 3,
    sdb: 2,
    surface: 95,
    categorie: 'appartement',
    equipements: ['Climatisation', 'Balcon', 'Wi-Fi', 'Groupe électrogène'],
    nouveau: false,
  },
  {
    id: 7,
    name: 'Maison avec jardin',
    emplacement: { ville: 'Ouagadougou', quartier: 'Kalgondin' },
    description:
      "Maison conviviale avec grand jardin et espace extérieur aménagé, parfaite pour une famille.",
    contact: '+226 66 33 22 11',
    prix: 75000,
    image: img('photo-1570129477492-45c003edd2be'),
    chambres: 3,
    sdb: 2,
    surface: 120,
    categorie: 'maison',
    equipements: ['Jardin', 'Garage', 'Eau courante'],
    nouveau: false,
  },
  {
    id: 8,
    name: 'Résidence sécurisée',
    emplacement: { ville: 'Ouagadougou', quartier: 'Somgandé' },
    description:
      "Résidence dans un quartier calme et sécurisé avec gardien 24h/24 et espaces verts communs.",
    contact: '+226 79 00 11 22',
    prix: 150000,
    image: img('photo-1600585154340-be6161a56a0c'),
    chambres: 4,
    sdb: 3,
    surface: 160,
    categorie: 'villa',
    equipements: ['Sécurité 24h', 'Jardin', 'Garage', 'Climatisation'],
    nouveau: true,
  },
  {
    id: 9,
    name: 'Studio étudiant',
    emplacement: { ville: 'Ouagadougou', quartier: 'Cissin' },
    description:
      "Petit studio fonctionnel proche des universités, avec connexion Wi-Fi et espace bureau.",
    contact: '+226 64 12 34 56',
    prix: 35000,
    image: img('photo-1560448204-e02f11c3d0e2'),
    chambres: 1,
    sdb: 1,
    surface: 25,
    categorie: 'studio',
    equipements: ['Meublé', 'Wi-Fi'],
    nouveau: false,
  },
  {
    id: 10,
    name: 'Villa duplex haut standing',
    emplacement: { ville: 'Ouagadougou', quartier: 'Karpala' },
    description:
      "Duplex moderne avec finitions haut de gamme, piscine et grande terrasse panoramique.",
    contact: '+226 75 98 76 54',
    prix: 320000,
    image: img('photo-1600607687939-ce8a6c25118c'),
    chambres: 5,
    sdb: 4,
    surface: 300,
    categorie: 'villa',
    equipements: ['Piscine', 'Terrasse', 'Garage', 'Climatisation', 'Sécurité 24h'],
    nouveau: true,
  },
  {
    id: 11,
    name: 'Appartement duplex',
    emplacement: { ville: 'Ouagadougou', quartier: 'Dassasgho' },
    description:
      "Duplex élégant avec séjour spacieux, terrasse privée et cuisine moderne tout équipée.",
    contact: '+226 71 23 45 67',
    prix: 135000,
    image: img('photo-1600047509807-ba8f99d2cdde'),
    chambres: 3,
    sdb: 2,
    surface: 110,
    categorie: 'appartement',
    equipements: ['Terrasse', 'Climatisation', 'Wi-Fi', 'Groupe électrogène'],
    nouveau: false,
  },
  {
    id: 12,
    name: 'Immeuble à usage mixte',
    emplacement: { ville: 'Ouagadougou', quartier: 'Ouaga centre' },
    description:
      "Immeuble adapté aux bureaux et logements, emplacement stratégique au cœur de la capitale.",
    contact: '+226 72 34 56 78',
    prix: 600000,
    image: img('photo-1486406146926-c627a92ad1ab'),
    chambres: 8,
    sdb: 6,
    surface: 600,
    categorie: 'bureau',
    equipements: ['Groupe électrogène', 'Sécurité 24h', 'Parking', 'Ascenseur'],
    nouveau: false,
  },
  {
    id: 13,
    name: 'Bureau moderne en étage',
    emplacement: { ville: 'Bobo-Dioulasso', quartier: 'Zone du Bois' },
    description:
      "Plateau de bureaux lumineux avec climatisation et parking, idéal pour une entreprise en croissance.",
    contact: '+226 70 11 22 33',
    prix: 200000,
    image: img('photo-1497366216548-37526070297c'),
    chambres: 3,
    sdb: 2,
    surface: 140,
    categorie: 'bureau',
    equipements: ['Climatisation', 'Parking', 'Wi-Fi', 'Groupe électrogène'],
    nouveau: true,
  },
  {
    id: 14,
    name: 'Maison familiale spacieuse',
    emplacement: { ville: 'Koudougou', quartier: 'Centre-ville' },
    description:
      "Maison spacieuse avec grande cour arborée et deux salons, proche des écoles et du marché.",
    contact: '+226 76 44 55 66',
    prix: 65000,
    image: img('photo-1600566753086-00f18fb6b3ea'),
    chambres: 4,
    sdb: 2,
    surface: 150,
    categorie: 'maison',
    equipements: ['Jardin', 'Garage', 'Eau courante'],
    nouveau: false,
  },
  {
    id: 15,
    name: 'Appartement standing',
    emplacement: { ville: 'Bobo-Dioulasso', quartier: 'Bobo centre' },
    description:
      "Appartement de standing entièrement équipé avec vue dégagée et climatisation centrale.",
    contact: '+226 65 77 88 99',
    prix: 120000,
    image: img('photo-1600585154526-990dced4db0d'),
    chambres: 3,
    sdb: 2,
    surface: 100,
    categorie: 'appartement',
    equipements: ['Climatisation', 'Balcon', 'Wi-Fi', 'Ascenseur'],
    nouveau: true,
  },
  {
    id: 16,
    name: 'Studio confort',
    emplacement: { ville: 'Koudougou', quartier: 'Secteur 4' },
    description:
      "Studio confortable et lumineux, meublé avec goût, dans une résidence calme et sécurisée.",
    contact: '+226 79 33 44 55',
    prix: 40000,
    image: img('photo-1505691938895-1758d7feb511'),
    chambres: 1,
    sdb: 1,
    surface: 28,
    categorie: 'studio',
    equipements: ['Meublé', 'Climatisation', 'Wi-Fi'],
    nouveau: false,
  },
];

